### ISSUE TITLE
Please clean up your requirements.

### ISSUE THREAD

**Issue by amcgregor** [kevinadhiguna/bruce#1]
Exactly the same problem as per: kevinadhiguna/link-shortener#1 and kevinadhiguna/instagram-profpic-downloader#1 and kevinadhiguna/body-mass-index-calculator#1 and kevinadhiguna/ip-revealer#1 … the list has become long enough to not even include all. See the first referenced here for a full index of how bad this problem is.

Low quality bulk library creation with no use of the referenced libraries is pure spam.  Please correct this.

**Comment by kevinadhiguna** [comment]
Hello @amcgregor , thanks for letting me know!
I just made the [latest commit](https://github.com/kevinadhiguna/bruce/commit/7fbbd6b1085afd84656e93c2b21947d38b3ace4b) that should fix this issue. Please let me know if you have any questions, thanks !

**Comment by amcgregor** [comment]
Thank you very much, and apologies for the cross-project e-mail notification spam I must have triggered; thought you may wish to individually track corrections.

Thank you again! (Time for another spam-wave. 😭) Wave 2! 😀
